### ISSUE TITLE
EndtoEnd testing 

### ISSUE THREAD

**Issue by ArnaudGastinel** [juliawildmoka/TestQA#11]
MAGIC CREATE BRANCH

**Comment by ArnaudGastinel** [comment]
MAGIC CREATE BRANCH

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-11 created for repositories: A,B,C,TestQA
Branch QA-11 already created for repositories:

**Comment by ArnaudGastinel** [comment]
MAGIC PULL REQUEST

**Comment by ArnaudGastinel** [comment]
MAGIC PULL REQUEST

**Comment by ArnaudGastinel** [comment]
MAGIC CREATE PULL REQUEST

**Comment by ArnaudGastinel** [comment]
MAGIC CREATE PULL REQUEST

**Comment by ArnaudGastinel** [comment]
MAGIC MERGE

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-11 on repositories A are going to be merged into master

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request creation is not needed

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request creation is not needed

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request creation is not needed

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request creation is not needed

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request created on QA-11 for repositories: A

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request created on QA-11 for repositories: A
