### ISSUE TITLE
Testing comment at creation

### ISSUE THREAD

**Issue by ArnaudGastinel** [juliawildmoka/TestQA#15]
MAGIC CREATE BRANCHES

**Comment by ArnaudGastinel** [comment]
MAGIC CREATE BRANCHES

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-15 created for repositories: B,C,TestQA
Branch QA-15 already created for repositories: A

**Comment by ArnaudGastinel** [comment]
MAGIC PULL REQUEST

**Comment by ArnaudGastinel** [comment]
MAGIC PULL REQUEST

**Comment by ArnaudGastinel** [comment]
MAGIC CREATE PULL REQUEST

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request created on QA-15 for repositories: A

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request already exist on another repository, pull request created on branch QA-15 for repository: B

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request creation is not needed

**Comment by ArnaudGastinel** [comment]
MAGIC CREATE BRANCHES

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-15 created for repositories: D
Branch QA-15 already created for repositories: A,B,C,TestQA

**Comment by ArnaudGastinel** [comment]
MAGIC CREATE BRANCHES

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-15 created for repositories: 
Branch QA-15 already created for repositories: A,B,C,D,TestQA

**Comment by ArnaudGastinel** [comment]
MAGIC CREATE BRANCHES

**Comment by ArnaudGastinel** [comment]
MAGIC CREATE BRANCHES
http://192.168.84.197:8080/job/DevProcessAutomationHook/171/

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-15 created for repositories: 
Branch QA-15 already created for repositories: A,B,C,D,TestQA
