### ISSUE TITLE
Test comment edition

### ISSUE THREAD

**Issue by ArnaudGastinel** [juliawildmoka/TestQA#17]

**Comment by ArnaudGastinel** [comment]
MAGIC CREATE BRANCHES
http://192.168.84.197:8080/job/DevProcessAutomationHook/179/

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-17 created for repositories: A,B,C,D,TestQA
Branch QA-17 already created for repositories:

**Comment by ArnaudGastinel** [comment]
MAGIC CREATE PULL REQUESTS
http://192.168.84.197:8080/job/DevProcessAutomationHook/186/

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request created on QA-17 for repositories: A

**Comment by ArnaudGastinel** [comment]
MAGIC MERGE

**Comment by ArnaudGastinel** [comment]
MAGIC MERGE

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-17 on repositories A are going to be merged into master

**Comment by ArnaudGastinel** [comment]
MAGIC MERGE
http://192.168.84.197:8080/job/DevProcessAutomationHook/191/

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-17 on repositories A are going to be merged into master

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-17 on repositories A has been merged into master
