### ISSUE TITLE
no PR build status

### ISSUE THREAD

**Issue by juliawildmoka** [juliawildmoka/TestQA#18]

**Comment by juliawildmoka** [comment]
MAGIC CREATE BRANCHES
http://192.168.84.197:8080/job/DevProcessAutomationHook/204/

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-18 created for repositories: B,D,TestQA
Branch QA-18 already created for repositories: A,C

**Comment by juliawildmoka** [comment]
MAGIC CREATE PULL REQUEST
http://192.168.84.197:8080/job/DevProcessAutomationHook/211/

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request created on QA-18 for repositories: C

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request already exist on another repository, pull request created on branch QA-18 for repository: D

**Comment by thomas-thenus-at-wildmoka** [comment]
MAGIC REBUILD

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request 'MAGIC pull request creation for issue #QA-18' on C is not mergeable and so not buildable

**Comment by thomas-thenus-at-wildmoka** [comment]
MAGIC REBUILD

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request 'MAGIC pull request creation for issue #QA-18' on C is not mergeable and so not buildable

**Comment by thomas-thenus-at-wildmoka** [comment]
MAGIC REBUILD
Master has changed from issue 42
http://192.168.84.197:8080/job/DevProcessAutomationHook/840/

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request 'MAGIC pull request creation for issue #QA-18' on C is not mergeable and so not buildable
