### ISSUE TITLE
deleted my branches

### ISSUE THREAD

**Issue by juliawildmoka** [juliawildmoka/TestQA#20]

**Comment by juliawildmoka** [comment]
MAGIC CREATE BRANCHES
http://192.168.84.197:8080/job/DevProcessAutomationHook/242/

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-20 created for repositories: A,B,C,D,TestQA

**Comment by juliawildmoka** [comment]
MAGIC MERGE

http://192.168.84.197:8080/job/DevProcessAutomationHook/248/

**Comment by thomas-thenus-at-wildmoka** [comment]
No repository has Pull Request for Branch QA-20 to merge into master

**Comment by thomas-thenus-at-wildmoka** [comment]
No merge needed, no repository has Pull Request for Branch QA-20 to merge

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-20 deleted for repositories: A,B,C,D,TestQA

**Comment by juliawildmoka** [comment]
MAGIC CREATE BRANCHES
http://192.168.84.197:8080/job/DevProcessAutomationHook/256/

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-20 created for repositories: A,B,C,D,TestQA

**Comment by juliawildmoka** [comment]
MAGIC CREATE PULL REQUEST
http://192.168.84.197:8080/job/DevProcessAutomationHook/262/

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request creation is not needed

**Comment by juliawildmoka** [comment]
MAGIC CREATE PULL REQUEST
http://192.168.84.197:8080/job/DevProcessAutomationHook/264/

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request creation is not needed

**Comment by juliawildmoka** [comment]
MAGIC CREATE BRANCHES

http://192.168.84.197:8080/job/DevProcessAutomationHook/266/

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-20 already created for repositories: A,B,C,D,TestQA

**Comment by juliawildmoka** [comment]
MAGIC CREATE PULL REQUEST
http://192.168.84.197:8080/job/DevProcessAutomationHook/270/

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request created on QA-20 for repositories: C,D

**Comment by thomas-thenus-at-wildmoka** [comment]
MAGIC REBUILD

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request 'MAGIC pull request creation for issue #QA-20' on C is not mergeable and so not buildable

**Comment by thomas-thenus-at-wildmoka** [comment]
MAGIC REBUILD

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request 'MAGIC pull request creation for issue #QA-20' on C is not mergeable and so not buildable

**Comment by thomas-thenus-at-wildmoka** [comment]
MAGIC REBUILD
Master has changed from issue 42
http://192.168.84.197:8080/job/DevProcessAutomationHook/841/

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request 'MAGIC pull request creation for issue #QA-20' on C is not mergeable and so not buildable
