### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by ArnaudGastinel** [juliawildmoka/TestQA#26]
MAGIC CREATE BRANCHES
http://www.google.com
http://www.google.com

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-26 created for repositories: A,B,C,D,Ignore1,Ignore2,TestQA

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-26 already created for repositories: A,B,C,D,Ignore1,Ignore2,TestQA
