### ISSUE TITLE
Test fix

### ISSUE THREAD

**Issue by ArnaudGastinel** [juliawildmoka/TestQA#29]
MAGIC CREATE BRANCHES
http://192.168.84.197:8080/job/DevProcessAutomationHook/319/

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-29 created for repositories: A,B,C,D,TestQA

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request has been created manually on another repo, begin automatic creation of pull requests. 
http://192.168.84.197:8080/job/DevProcessAutomationHook/430/

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request creation is not needed

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-29 on repositories A can be merged into master and a build will be done
