### ISSUE TITLE
AUTO

### ISSUE THREAD

**Issue by juliawildmoka** [juliawildmoka/TestQA#33]
MAGIC CREATE BRANCHES
http://192.168.84.197:8080/job/DevProcessAutomationHook/407/

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-33 created for repositories: A,B,C,D,TestQA

**Comment by juliawildmoka** [comment]
MAGIC CREATE BRANCHES
http://192.168.84.197:8080/job/DevProcessAutomationHook/413/

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-33 already created for repositories: A,B,C,D,TestQA

**Comment by juliawildmoka** [comment]
MAGIC CREATE PULL REQUEST

http://192.168.84.197:8080/job/DevProcessAutomationHook/417/

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request created on QA-33 for repositories: B,C

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-33 on repositories B,C can be merged into master and a build will be done

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-33 on repositories B,C can be merged into master and a build will be done

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request already exist on another repository, pull request created on branch QA-33 for repository: D

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-33 on repositories B,C,D can be merged into master and a build will be done

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-33 on repositories B,C,D can be merged into master and a build will be done

**Comment by juliawildmoka** [comment]
MAGIC MERGE
http://192.168.84.197:8080/job/DevProcessAutomationHook/434/

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-33 on repositories B,C,D will be merged into master

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-33 on repositories B,C,D has been merged into master

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-33 deleted for repositories: A,B,C,D,TestQA

**Comment by juliawildmoka** [comment]
MAGIC CREATE BRANCHES

http://192.168.84.197:8080/job/DevProcessAutomationHook/445/

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-33 created for repositories: A,B,C,D,TestQA

**Comment by juliawildmoka** [comment]
MAGIC CREATE PULL REQUEST
http://192.168.84.197:8080/job/DevProcessAutomationHook/458/

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request created on QA-33 for repositories: A

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request has been created manually on another repo, begin automatic creation of pull requests. 
http://192.168.84.197:8080/job/DevProcessAutomationHook/459/

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-33 on repositories A can be merged into master and a build will be done

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request creation is not needed

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-33 on repositories A can be merged into master and a build will be done
