### ISSUE TITLE
Test manual

### ISSUE THREAD

**Issue by ArnaudGastinel** [juliawildmoka/TestQA#34]
MAGIC CREATE BRANCH
http://192.168.84.197:8080/job/DevProcessAutomationHook/452/

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-34 created for repositories: A,B,C,D,TestQA

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request has been created manually on another repo, begin automatic creation of pull requests. 
http://192.168.84.197:8080/job/DevProcessAutomationHook/466/

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request creation is not needed

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-34 on repositories A can be merged into master and a build will be done

**Comment by ArnaudGastinel** [comment]
MAGIC REBUILD

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-34 on repositories A can be merged into master and a build will be done

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-34 on repositories A can be merged into master and a build will be done

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-34 on repositories A can be merged into master and a build will be done

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-34 on repositories A can be merged into master and a build will be done

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-34 on repositories A can be merged into master and a build will be done

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-34 on repositories A can be merged into master and a build will be done

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-34 on repositories A can be merged into master and a build will be done

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-34 on repositories A can be merged into master and a build will be done
