### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by ArnaudGastinel** [juliawildmoka/TestQA#36]
MAGIC CREATE BRANCHES
http://192.168.84.197:8080/job/DevProcessAutomationHook/634/

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-36 created for repositories: A,B,C,D,TestQA

**Comment by ArnaudGastinel** [comment]
MAGIC CREATE PULL request
http://192.168.84.197:8080/job/DevProcessAutomationHook/640/

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request creation is not needed

**Comment by thomas-thenus-at-wildmoka** [comment]
No repository has Pull Request for Branch QA-36 to merge into master and no build is needed

**Comment by ArnaudGastinel** [comment]
MAGIC CREATE PULL request
http://192.168.84.197:8080/job/DevProcessAutomationHook/644/

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request created on QA-36 for repositories: B

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-36 on repositories B can be merged into master and a build will be done

**Comment by thomas-thenus-at-wildmoka** [comment]
MAGIC MERGE
http://192.168.84.197:8080/job/DevProcessAutomationHook/647/

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-36 on repositories B will be merged into master

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-36 on repositories B has been merged into master

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-36 deleted for repositories: A,B,C,D,TestQA
