### ISSUE TITLE
magic create branches

### ISSUE THREAD

**Issue by juliawildmoka** [juliawildmoka/TestQA#38]
magic create branches
http://192.168.84.197:8080/job/DevProcessAutomationHook/670/

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-38 created for repositories: A,B,C,D,TestQA

**Comment by juliawildmoka** [comment]
MAGIC CREATE PULL REQUEST
http://192.168.84.197:8080/job/DevProcessAutomationHook/682/

**Comment by juliawildmoka** [comment]
MAGIC MERGE

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request created on QA-38 for repositories: C

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request 'AUTO Pull request created for issue #QA-38' on C is not mergeable and so not buildable

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-38 on C has not a successful build state
Pull request 'AUTO Pull request created for issue #QA-38' on C not mergeable

**Comment by thomas-thenus-at-wildmoka** [comment]
MAGIC REBUILD

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request 'AUTO Pull request created for issue #QA-38' on C is not mergeable and so not buildable

**Comment by thomas-thenus-at-wildmoka** [comment]
MAGIC REBUILD
Master has changed from issue 42
http://192.168.84.197:8080/job/DevProcessAutomationHook/843/

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request 'AUTO Pull request created for issue #QA-38' on C is not mergeable and so not buildable
