### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by juliawildmoka** [juliawildmoka/TestQA#40]
MAGIC CREATE BRANCHES
http://192.168.84.197:8080/job/DevProcessAutomationHook/754/

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-40 created for repositories: A,B,C,D,TestQA

**Comment by juliawildmoka** [comment]
MAGIC CREATE PULL REQUEST
http://192.168.84.197:8080/job/DevProcessAutomationHook/762/

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request created on QA-40 for repositories: A

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-40 on repositories A can be merged into master and a build will be done

**Comment by thomas-thenus-at-wildmoka** [comment]
Build finished with status: success.

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request already exist on another repository, pull request created on branch QA-40 for repository: B

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-40 on repositories A,B can be merged into master and a build will be done

**Comment by thomas-thenus-at-wildmoka** [comment]
Build finished with status: success.

**Comment by thomas-thenus-at-wildmoka** [comment]
MAGIC REBUILD
Master has changed from issue 42
http://192.168.84.197:8080/job/DevProcessAutomationHook/838/

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request 'AUTO Pull request created for issue #QA-40' on A is not mergeable and so not buildable
Pull request 'AUTO Pull request created for issue #QA-40' on B is not mergeable and so not buildable
