### ISSUE TITLE
Negative test

### ISSUE THREAD

**Issue by juliawildmoka** [juliawildmoka/TestQA#41]
MAGIC CREATE PULL REQUEST

**Comment by juliawildmoka** [comment]
MAGIC MERGE

**Comment by thomas-thenus-at-wildmoka** [comment]
No repository has Pull Request for Branch QA-41 to merge into master

**Comment by juliawildmoka** [comment]
MAGIC CREATE PULL REQUEST
http://192.168.84.197:8080/job/DevProcessAutomationHook/798/
