### ISSUE TITLE
Full-cycle

### ISSUE THREAD

**Issue by juliawildmoka** [juliawildmoka/TestQA#42]
MAGIC CREATE BRANCHES
http://192.168.84.197:8080/job/DevProcessAutomationHook/799/

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-42 created for repositories: A,B,C,D,TestQA

**Comment by juliawildmoka** [comment]
MAGIC CREATE BRANCHES
http://192.168.84.197:8080/job/DevProcessAutomationHook/807/

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-42 already created for repositories: A,B,C,D,TestQA

**Comment by juliawildmoka** [comment]
MAGIC CREATE PULL REQUEST

http://192.168.84.197:8080/job/DevProcessAutomationHook/809/

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request created on QA-42 for repositories: B,D

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-42 on repositories B,D can be merged into master and a build will be done

**Comment by thomas-thenus-at-wildmoka** [comment]
Build finished with status: success.

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request already exist on another repository, pull request created on branch QA-42 for repository: C

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-42 on repositories B,C,D can be merged into master and a build will be done

**Comment by thomas-thenus-at-wildmoka** [comment]
Build finished with status: failure.

**Comment by juliawildmoka** [comment]
MAGIC MERGE

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-42 on B has not a successful build state
Branch QA-42 on C has not a successful build state
Branch QA-42 on D has not a successful build state

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request already exist on another repository, pull request created on branch QA-42 for repository: A

**Comment by thomas-thenus-at-wildmoka** [comment]
Pull request for Branch QA-42 on repositories A,B,C,D can be merged into master and a build will be done

**Comment by thomas-thenus-at-wildmoka** [comment]
Build finished with status: success.

**Comment by juliawildmoka** [comment]
MAGIC MERGE
http://192.168.84.197:8080/job/DevProcessAutomationHook/824/

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-42 on repositories A,B,C,D will be merged into master

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-42 on repositories A,B,C,D has been merged into master

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-42 deleted for repositories: A,B,C,D,TestQA

**Comment by juliawildmoka** [comment]
MAGIC CREATE BRANCHES
http://192.168.84.197:8080/job/DevProcessAutomationHook/852/

**Comment by thomas-thenus-at-wildmoka** [comment]
Branch QA-42 created for repositories: A,B,C,D,TestQA
